services:
  schlage-app:
    build: .
    container_name: schlage-app
    restart: unless-stopped
    networks:
      - traefik-br8b_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.schlage-docker.rule=Host(\"schlage.henrimc.tech\")"
      - "traefik.http.routers.schlage-docker.entrypoints=websecure"
      - "traefik.http.routers.schlage-docker.tls=true"
      - "traefik.http.services.schlage-docker.loadbalancer.server.port=8000"

networks:
  traefik-br8b_default:
    external: true

volumes:
  schlage-data:
